### ISSUE TITLE
Tab Bar Selection

### ISSUE THREAD

**Issue by philipjpark** [CodePath-iOS-Final-Project/GymSwift#16]
- User can view 1 selection per row (buddy selection, accountability, workout journal).
- User can select an option and be prompted to the next screen.

**Comment by Rebecca-CYLi** [comment]
Changed to Tab Bar Navigation Selection

- 5 tab bars on the bottom for navigation between screens:
          - [ ] 1. Map
          - [ ] 2. Accountability Posts/Tweets
          - [ ] 3. Personal Workout Journal
          - [ ] 4. Chat Messages
          - [ ] 5. Settings

**Comment by philipjpark** [comment]
Looks good!
